### ISSUE TITLE
Is it in the roadmap to support newer versions of firebase? 

### ISSUE THREAD

**Issue by SergioZgz** [TobiasBuchholz/Plugin.Firebase#395]
Is the roadmap supporting 121.6.2 or higher?

Anyway thanks for your amazing work :)

**Comment by AdamEssenmacher** [comment]
Does the plugin not work with 121.6.2 or higher?

**Comment by SergioZgz** [comment]
I get an exception, Im using analytics and crash lyrics. 

I'm using MTAdmob, with 1.5.1 works fine, but 1.6.0 or higher need 121.6.2 or higher and then I get exception calling measurement/zzef.

**Comment by AdamEssenmacher** [comment]
Can you share the details of the exception? Message / stack trace?

**Comment by SergioZgz** [comment]
When install MTAdmob 1.6.0 and Plugin.Firebase I get a R8 issue because MTAdmob use PlayServices Measurement higher than Plugin.Firebase. To Fix it I force install Xamarin.GooglePlayServices.Measurement and .base, .impl, .sdk 121.6.2 (or higher)... The project compile but then i get this...


> Java.Lang.NoSuchMethodError: 'No static method zzg(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/os/Bundle;)Lcom/google/android/gms/internal/measurement/zzef; in class Lcom/google/android/gms/internal/measurement/zzef; or its super classes (declaration of 'com.google.android.gms.internal.measurement.zzef' appears in /data/app/~~X2_HnW1XRsIqL26eOMFkXA==/xxxxxxxx.yyyyyyyy.com-EJikrKNOwcbg7se50UsHcQ==/base.apk!classes2.dex)'


> [FirebaseCrashlytics] Initializing Firebase Crashlytics 18.3.2 for xxxxxxx.yyyyyy.com
> [AndroidRuntime] Shutting down VM
> [AndroidRuntime] FATAL EXCEPTION: main
> [AndroidRuntime] Process: xxxxxxx.yyyyyy.com, PID: 9266
> [AndroidRuntime] java.lang.NoSuchMethodError: No static method zzg(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/os/Bundle;)Lcom/google/android/gms/internal/measurement/zzef; in class Lcom/google/android/gms/internal/measurement/zzef; or its super classes (declaration of 'com.google.android.gms.internal.measurement.zzef' appears in /data/app/~~X2_HnW1XRsIqL26eOMFkXA==/xxxxxxx.yyyyyy.com-EJikrKNOwcbg7se50UsHcQ==/base.apk!classes2.dex)
> [AndroidRuntime] 	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(com.google.android.gms:play-services-measurement-api@@21.3.0:12)
> [AndroidRuntime] 	at com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar.lambda$getComponents$0(com.google.android.gms:play-services-measurement-api@@21.3.0:4)
> [AndroidRuntime] 	at com.google.firebase.analytics.connector.internal.zzb.create(Unknown Source:0)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:160)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda2.get(D8$$SyntheticClass:0)
> [AndroidRuntime] 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.lambda$init$2$com-google-firebase-crashlytics-AnalyticsDeferredProxy(AnalyticsDeferredProxy.java:86)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy$$ExternalSyntheticLambda2.handle(D8$$SyntheticClass:0)
> [AndroidRuntime] 	at com.google.firebase.components.OptionalProvider.whenAvailable(OptionalProvider.java:77)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.init(AnalyticsDeferredProxy.java:82)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init>(AnalyticsDeferredProxy.java:63)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init>(AnalyticsDeferredProxy.java:49)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:83)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:60)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$XFR966Xtld0zGICMasGRYAhWin4(Unknown Source:0)
> [AndroidRuntime] 	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(D8$$SyntheticClass:0)
> [AndroidRuntime] 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
> [AndroidRuntime] 	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(D8$$SyntheticClass:0)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:160)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda2.get(D8$$SyntheticClass:0)
> [AndroidRuntime] 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
> [AndroidRuntime] 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
> [AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
> [AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
> [AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
> [AndroidRuntime] 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
> [AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
> [AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2650)
> [AndroidRuntime] 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2620)
> [AndroidRuntime] 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
> [AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:8378)
> [AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7889)
> [AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7576)
> [AndroidRuntime] 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> [AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
> [AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
> [AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:257)
> [AndroidRuntime] 	at android.os.Looper.loop(Looper.java:368)
> [AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8839)
> [AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
> [AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
> [AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> [monodroid-assembly] open_from_bundles: failed to load bundled assembly System.Console.dll
> [monodroid-assembly] open_from_bundles: the assembly might have been uploaded to the device with FastDev instead
> Loaded assembly: /data/data/xxxxxxx.yyyyyy.com/files/.__override__/arm64-v8a/System.Console.dll [External]
>

**Comment by AdamEssenmacher** [comment]
Thank you.

We try to use the lowest versions of the native platform binding packages needed for this plugin to work. It is often the case that the plugin will continue to work just fine across major version bumps. However, breaking changes to the API surface will cause errors like this, which is when we update. So, sounds like it's just PR time to bump the plugin's Android dependencies.

As an aside, if you're using https://www.nuget.org/packages/Plugin.MauiMTAdmob/1.6.0 I'd be concerned about incompatibility with this plugin on the iOS side, since that package has a dependency on the deprecated Xamarin.Firebase.iOS.Core package. That could cause build or runtime issues with AdamE.Firebase.iOS.Core.

**Comment by SergioZgz** [comment]
Right now, i'm o 1.5.1, i would like upgrade to 1.7.1 but I'm not in a hurry to do it right now, with 1.5.1 its ok for me.

About the issue with iOS side.... I dont use admob on iOS right now, but thanks for tell me about that

**Comment by SergioZgz** [comment]
Thank you for everything @AdamEssenmacher !

**Comment by AdamEssenmacher** [comment]
Let's leave this open until we can make the updates. We rely on reports like this to know when it's time to bump packages up.

**Comment by SergioZgz** [comment]
Hi @AdamEssenmacher !

Do you have more or less a date in mind for this?

**Comment by AdamEssenmacher** [comment]
Taking a closer look at this, the Xamarin.GooglePlayServices.Measurement* packages are all transient dependencies of Xamarin.Firebase.Analytics. Have you tried updating Xamarin.Firebase.Analytics itself to 121.6.2+?

**Comment by SergioZgz** [comment]
I could have sworn that's what I did, but I'll try it again and let you know :)

**Comment by SergioZgz** [comment]
Well, I must have done something wrong.... now it works, it doesn't load the other library ads in version 1.7.1 but I'm checking it, otherwise ... you were right, thank you very much :)
